[bitbake]
src_uri = git://git.openembedded.org/bitbake
dest_dir = bitbake
branch = stable/2.8-nut
last_revision = 0880963fea4d91a034e4a6e007d23f98658ab986
file_exclude = classes/base.bbclass conf/bitbake.conf .gitignore MANIFEST.in setup.py TODO

[oe-core]
src_uri = git://git.openembedded.org/openembedded-core
dest_dir = .
branch = stable/scarthgap-nut
last_revision = 737293bead3e7b994347e47f09bc69437479d50c
file_exclude = meta/conf/templates/default/bblayers.conf.sample meta/conf/templates/default/local.conf.sample meta/conf/templates/default/local.conf.sample.extended meta/conf/templates/default/site.conf.sample

[yocto-docs]
branch = scarthgap
src_uri = git://git.yoctoproject.org/yocto-docs
dest_dir = .
file_filter = documentation/
last_revision = 76f4b5ded4aa04ca1404510f0232593a968e0f66

[meta-yocto]
branch = stable/scarthgap-nut
src_uri = git://git.yoctoproject.org/meta-yocto
dest_dir = .
last_revision = ca5a51aadaf651881d640688dc3e1e123aa30bf6

