[bitbake]
src_uri = git://git.openembedded.org/bitbake
dest_dir = bitbake
branch = stable/2.8-nut
last_revision = 0880963fea4d91a034e4a6e007d23f98658ab986
file_exclude = classes/base.bbclass conf/bitbake.conf .gitignore MANIFEST.in setup.py TODO

[oe-core]
src_uri = git://git.openembedded.org/openembedded-core
dest_dir = .
branch = stable/scarthgap-nut
last_revision = 3217490cc554069ae53aa54cf8ad7327ce85fa10
file_exclude = meta/conf/templates/default/bblayers.conf.sample meta/conf/templates/default/local.conf.sample meta/conf/templates/default/local.conf.sample.extended meta/conf/templates/default/site.conf.sample

[yocto-docs]
branch = scarthgap
src_uri = git://git.yoctoproject.org/yocto-docs
dest_dir = .
file_filter = documentation/
last_revision = 51c53ef1e8b4ec4afbb84252e59dd5501f405064

[meta-yocto]
branch = stable/scarthgap-nut
src_uri = git://git.yoctoproject.org/meta-yocto
dest_dir = .
last_revision = 2f749ae477c3b94dce71038f025180d7f612dab0

