[bitbake]
src_uri = git://git.openembedded.org/bitbake
local_repo_dir = /home/yocon/Documents/projets/yocto/maint_lts/bitbake
dest_dir = bitbake
branch = stable/2.8-nut
last_revision = 10118785e4a670bce4980e1044c0888a8b6e84af
hook = /home/yocon/Documents/projets/yocto/maint_lts/poky-config/combo-layerhook-bitbake.sh
file_exclude = classes/base.bbclass conf/bitbake.conf .gitignore MANIFEST.in setup.py TODO

[oe-core]
src_uri = git://git.openembedded.org/openembedded-core
local_repo_dir = /home/yocon/Documents/projets/yocto/maint_lts/openembedded-core
dest_dir = .
branch = stable/scarthgap-nut
last_revision = a9a785d7fa0cfe2a9087dbcde0ef9f0d2a441375
hook = /home/yocon/Documents/projets/yocto/maint_lts/poky-config/combo-layerhook-oecore.sh
file_exclude = meta/conf/templates/default/bblayers.conf.sample meta/conf/templates/default/local.conf.sample meta/conf/templates/default/local.conf.sample.extended meta/conf/templates/default/site.conf.sample

[yocto-docs]
branch = scarthgap
src_uri = git://git.yoctoproject.org/yocto-docs
local_repo_dir = /home/yocon/Documents/projets/yocto/maint_lts/yocto-docs
dest_dir = .
file_filter = documentation/
last_revision = e7cbf979deb9739ee4b968672d4b03ae65b24424
hook = /home/yocon/Documents/projets/yocto/maint_lts/poky-config/combo-layerhook-yoctodocs.sh

[meta-yocto]
branch = stable/scarthgap-nut
src_uri = git://git.yoctoproject.org/meta-yocto
local_repo_dir = /home/yocon/Documents/projets/yocto/maint_lts/meta-yocto
dest_dir = .
last_revision = 94d19f9d8392f8a125764df0f8eda04205c7e76c
hook = /home/yocon/Documents/projets/yocto/maint_lts/poky-config/combo-layerhook-metayocto.sh

